name: Bug report
description: Create an issue for bug reporting or error reporting.
body:
    - type: markdown
      attributes:
          value: >
              Thank you for reporting an issue.

              This issue tracker is for reporting bugs and errors found in `next-storyblok`
              (https://github.com/black-tape-project/next-storyblok).

              If you have a question about how to achieve something or are struggling
              in anyway, please post a question inside of the discussions tab:
              https://github.com/black-tape-project/next-storyblok/discussions

              **Before submitting a new bug/issue, please check the links below to see
              if there is a solution or question posted there already.**

              #### Issues Tab

              https://github.com/black-tape-project/next-storyblok/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

              #### Closed Issues Tab

              https://github.com/black-tape-project/next-storyblok/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed

              #### Discussions Tab

              https://github.com/black-tape-project/next-storyblok/discussions

              The more information you fill in, the better the community can help you.
    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          description: >-
              Provide a clear and concise description of the challenge you are running into.
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: Steps to reproduce the bug or error
          description: Describe the steps to reproduce the behavior.
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
      validations:
          required: true
    - type: textarea
      id: additional
      attributes:
          label: Additional context
          description: Add any other context about the problem here.
