blank_issues_enabled: false
contact_links:
    - name: Feature Requests & Questions
      url: https://github.com/black-tape-project/next-storyblok/discussions
      about: Ask anything that isn't bug or error related here.
